### ISSUE TITLE
Occasionally File does not copy 

### ISSUE THREAD

**Issue by amneo** [amneo/DocumentCompiler#9]
What happened: Third Party certificate path and file name was provided However it never got copied to the  UL folder. 

Possible reason:
1. Source File name too long
2. Permission issues. Since this happened with first time run.

**Comment by whench18** [comment]
hi, is one possible cause of your problem is a too long path, I suggest, you should try the new long path tool. This will help you solve all kinds of path too long problems and will make your work fast and easy. thanks

**Comment by amneo** [comment]
hi whench18, Thanks for the input. My first preference would be to get it fixed without calling a third party tool. As of now we have a work around by shortening the file name and folder name.

**Comment by amneo** [comment]
For now it works added extra check with file exists function
